name: "Rob's Personal Blog"
favicon: null
layout_spectrum: 0.24174
typography_spectrum: 0.22106
title: Live Simply
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74850211-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
